# Generated by Django 3.0 on 2020-11-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=300)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Proyecto')),
            ],
        ),
    ]
