# Generated by Django 3.0 on 2020-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria_proyectos'),
        ),
    ]
