# Generated by Django 3.0 on 2020-11-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20201109_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='galeria_proyectos')),
                ('img_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Proyecto')),
            ],
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
