# Generated by Django 3.0 on 2021-01-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20201110_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='img_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='img',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Imagenes'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='principales'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de categoria'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion'),
        ),
    ]
