# Generated by Django 3.0 on 2021-01-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20210114_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='nombre_proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.Proyecto'),
        ),
    ]
