# Generated by Django 3.0 on 2021-01-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20210116_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Proyecto'),
        ),
    ]
