# Generated by Django 3.0 on 2021-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_imagen_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
