# Generated by Django 3.0 on 2021-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_auto_20210116_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='arquitecto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Arquitecto'),
        ),
    ]
