# Generated by Django 3.0 on 2021-02-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_auto_20210125_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fofografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['-id'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterField(
            model_name='imagen',
            name='resumen',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Explicacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Memoria'),
        ),
    ]
