# Generated by Django 3.0 on 2021-02-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_auto_20210202_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='arquitecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='A#o'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Equipo de proyecto'),
        ),
    ]
