# Generated by Django 3.0 on 2021-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_auto_20210208_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['id'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['orden'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
